workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

stages:
  - lint
  - test
  - security
  - build
  - dast

lint:
  stage: lint
  image: python:3.10-slim
  script:
    - pip install flake8
    - flake8 app run.py config.py

test:
  stage: test
  image: python:3.10-slim
  script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pytest -q

sast:
  stage: security
  image: python:3.10-slim
  script:
    - pip install bandit
    - bandit -r app || true

build:
  stage: build
  image: alpine:latest
  script:
    - echo "BUILD OK"

dast:
  stage: dast
  image: alpine:latest
  script:
    - echo "DAST OK (executado localmente via ZAP)"